MGMT-2858 LogsSender: added coredump and dmesg
openshift/assisted-installer-agent pull request #107
Opened 2020-12-01 14:30 UTC by danielerez

Added system-coredump file and dmesg output to logs collector
(should be added to each host logs tar in case of installation error).

2020-12-01 14:33 UTC, danielerez commented
@YuviGold @tsorya @yevgeny-shnaidman @osherdp @ybettan PTAL

2020-12-01 14:33 UTC, danielerez commented
/assign @YuviGold

2020-12-01 15:30 UTC, YuviGold commented on src/logs_sender/send_logs.go
> +		log.WithError(err).Errorf("Failed to copy coredump file")
Failed to get core dump file. This isn't really copying anything.
Does this file always exist?

2020-12-01 15:38 UTC, ybettan commented on src/logs_sender/send_logs.go
> +	stderr, exitCode := l.ExecuteOutputToFile(outputFilePath, "bash", "-c", cmd)
Is this working well? I know for sure that not separating the args in `ExecutePrivilegedCommand` isn't working well (maybe because on `nsester`)

2020-12-01 15:43 UTC, ybettan commented on src/logs_sender/send_logs.go
> +func gatherErrorLogs(l LogsSender, logsTmpFilesDir string) error {
If you make this function and interface method you will be able to mock it entirely instead of mocking all it internal separately

2020-12-01 15:46 UTC, ybettan commented on src/logs_sender/send_logs_test.go
> +		config.LogsSenderConfig.InstallerGatherlogging = false
Maybe you can add a different `It` for testing `GatherErrorLogs` once you make it part of the interfce, same way as we do for `GatherInstallerLogs`

2020-12-01 15:51 UTC, osherdp requested changes

2020-12-01 15:51 UTC, osherdp commented on src/logs_sender/send_logs.go
> +	cmd := "cat $(sysctl kernel.core_pattern | cut -d '|' -f2 | cut -d ' ' -f1)"
do we have ``coredumpctl`` on our system?
might save a bit of the bash magic here

2020-12-01 15:51 UTC, osherdp commented on src/logs_sender/send_logs.go
> +	log.Infof("Copy coredump file")
It might be harder, but...
can we store all the core dumps?

2020-12-01 15:51 UTC, osherdp commented on src/logs_sender/send_logs.go
> +
can we get ``/var/log/messages`` as well?
I think it's different from ``dmesg`` and can be interesting as well

2020-12-01 15:58 UTC, danielerez commented on src/logs_sender/send_logs.go
> +		log.WithError(err).Errorf("Failed to copy coredump file")
ExecuteOutputToFile actually copies the output of the command into the specified file, but I can rephrase.
The coredump file should always exist in the host, but I can ignore the errors just to be on the safe side.

2020-12-01 15:58 UTC, danielerez commented on src/logs_sender/send_logs.go
> +	stderr, exitCode := l.ExecuteOutputToFile(outputFilePath, "bash", "-c", cmd)
Yes seems to work well, so should have enough permissions to run this bash command.

2020-12-01 15:58 UTC, danielerez commented on src/logs_sender/send_logs.go
> +func gatherErrorLogs(l LogsSender, logsTmpFilesDir string) error {
Indeed, just wasn't sure it worth exposing as interface just for tests.

2020-12-01 15:58 UTC, danielerez commented on src/logs_sender/send_logs_test.go
> +		config.LogsSenderConfig.InstallerGatherlogging = false
Right, but not sure we have much to test here though. I'll give it a try.

2020-12-01 15:58 UTC, danielerez commented on src/logs_sender/send_logs.go
> +	log.Infof("Copy coredump file")
You mean besides the system coredump? Which ones would be interesting?

2020-12-01 15:58 UTC, danielerez commented on src/logs_sender/send_logs.go
> +	cmd := "cat $(sysctl kernel.core_pattern | cut -d '|' -f2 | cut -d ' ' -f1)"
Yeah actually tried with coredumpctl, but seems 'No coredumps found.' on the machine,
so I've just included the system-coredump.

2020-12-01 15:58 UTC, danielerez commented on src/logs_sender/send_logs.go
> +
yeah looked for it,  but seems that rsyslog isn't running in the hosts.

2020-12-01 16:23 UTC, osherdp commented on src/logs_sender/send_logs.go
> +	log.Infof("Copy coredump file")
What happens when two segfaults happen? Will the second core dump override the first one?
I don't think so, so we should bring them both

Also, does ``coreos-installer`` will dump in the system's location or any other location?
It's very important because we have unexplained behavior when using ``coreos-installer`` that can be investigated only by core dumps

2020-12-01 16:23 UTC, osherdp commented on src/logs_sender/send_logs.go
> +	cmd := "cat $(sysctl kernel.core_pattern | cut -d '|' -f2 | cut -d ' ' -f1)"
k

2020-12-01 16:30 UTC, osherdp commented on src/logs_sender/send_logs.go
> +
ok
there's journalctl BTW?

2020-12-01 17:45 UTC, danielerez commented on src/logs_sender/send_logs.go
> +	log.Infof("Copy coredump file")
sure, I'll just include all coredump files.
iinm, core-installer should dump in same locationn. @YuviGold

2020-12-02 09:16 UTC, YuviGold commented on src/logs_sender/send_logs.go
> +	log.Infof("Copy coredump file")
Unfortunately, I have no idea where `coreos-installer` dumps to.

2020-12-02 09:22 UTC, romfreiman commented on src/logs_sender/send_logs.go
> +	log.Infof("Copy coredump file")
https://coreos.slack.com/archives/CUPJTHQ5P/p1605165310224300?thread_ts=1605057411.176200&cid=CUPJTHQ5P

2020-12-02 09:38 UTC, danielerez commented on src/logs_sender/send_logs.go
> +	log.Infof("Copy coredump file")
ok, so seems it's indeed the same location.

2020-12-02 13:09 UTC, YuviGold approved these changes
LGTM

2020-12-02 13:10 UTC, danielerez commented
/hold

2020-12-02 13:11 UTC, merged