NO-ISSUE collect logs from containers in Jenkins Post
openshift/assisted-installer-agent pull request #167
Opened 2021-02-11 16:35 UTC by nmagnezi

Currently collects from the following containers:
- dhcp
- subsystem_wiremock_1

2021-02-11 16:43 UTC, nmagnezi commented
/assign @YuviGold 
/assign @osherdp

2021-02-11 16:53 UTC, osherdp commented
/lgtm

2021-02-11 16:57 UTC, YuviGold commented
/hold
Until verified logs been archived in Jenkins.

2021-02-11 17:16 UTC, YuviGold commented
@nmagnezi 
```
19:13:02  + docker logs subsystem_wiremock_1
19:13:02  Error: No such container: subsystem_wiremock_1
19:13:02  + true
19:13:02  [Pipeline] sh
19:13:02  + docker logs dhcp
19:13:02  Error: No such container: dhcp
19:13:02  + true
19:13:02  [Pipeline] sh
19:13:03  + sudo journalctl TAG=agent '--since=1 hour ago'
```

2021-02-14 17:23 UTC, osherdp commented
/retest

2021-02-17 10:47 UTC, nmagnezi commented
testing http://assisted-jenkins.usersys.redhat.com/job/assisted-installer-agent/job/PR-167/9/console

2021-02-17 16:30 UTC, osherdp commented
/lgtm

2021-02-24 14:47 UTC, YuviGold commented
@nmagnezi any progress?

2021-03-01 11:50 UTC, nmagnezi commented
**Tested locally**

ends with:

```sh
Summarizing 1 Failure:

[Fail] Image availability tests [It] Small timeout
/home/nmagnezi/go/src/github.com/assisted-installer-agent/subsystem/container_image_availability_test.go:29

Ran 30 of 30 Specs in 365.287 seconds
FAIL! -- 29 Passed | 1 Failed | 0 Pending | 0 Skipped

DONE 1 tests, 1 failure in 366.181s
make[1]: *** [Makefile:39: _test] Error 1
make[1]: Leaving directory '/home/nmagnezi/go/src/github.com/assisted-installer-agent'
make: [Makefile:47: subsystem] Error 2 (ignored)
docker-compose -f ./subsystem/docker-compose.yml logs dhcpd > dhcpd.log &
docker-compose -f ./subsystem/docker-compose.yml logs wiremock > wiremock.log &
docker-compose -f ./subsystem/docker-compose.yml down
Stopping subsystem_agent_run_a2c00bc2987c ... done
Stopping subsystem_dhcpd_run_7f7d4ac24dfa ... done
Stopping subsystem_wiremock_1             ... done
Removing subsystem_agent_run_a2c00bc2987c ... done
Removing subsystem_dhcpd_run_7f7d4ac24dfa ... done
Removing subsystem_wiremock_1             ... done
Removing network subsystem_agent_network
```


But for some reason, I see the content in `wiremock.log` and not in `dhcpd.log`:

```sh
$ cat dhcpd.log
Attaching to
```

```sh
$ cat wiremock.log
Attaching to subsystem_wiremock_1
wiremock_1  | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
wiremock_1  | SLF4J: Defaulting to no-operation (NOP) logger implementation
wiremock_1  | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
wiremock_1  |  /$$      /$$ /$$                     /$$      /$$                     /$$
wiremock_1  | | $$  /$ | $$|__/                    | $$$    /$$$                    | $$
wiremock_1  | | $$ /$$$| $$ /$$  /$$$$$$   /$$$$$$ | $$$$  /$$$$  /$$$$$$   /$$$$$$$| $$   /$$
wiremock_1  | | $$/$$ $$ $$| $$ /$$__  $$ /$$__  $$| $$ $$/$$ $$ /$$__  $$ /$$_____/| $$  /$$/
wiremock_1  | | $$$$_  $$$$| $$| $$  \__/| $$$$$$$$| $$  $$$| $$| $$  \ $$| $$      | $$$$$$/
wiremock_1  | | $$$/ \  $$$| $$| $$      | $$_____/| $$\  $ | $$| $$  | $$| $$      | $$_  $$
wiremock_1  | | $$/   \  $$| $$| $$      |  $$$$$$$| $$ \/  | $$|  $$$$$$/|  $$$$$$$| $$ \  $$
wiremock_1  | |__/     \__/|__/|__/       \_______/|__/     |__/ \______/  \_______/|__/  \__/
wiremock_1  |
wiremock_1  | port:                         8362
wiremock_1  | enable-browser-proxying:      false
wiremock_1  | disable-banner:               false
wiremock_1  | no-request-journal:           false
wiremock_1  | verbose:                      false
wiremock_1  |
wiremock_1  | 2021-03-01 11:37:00.385
wiremock_1  |                                                Request was not matched
wiremock_1  |                                                =======================
wiremock_1  |
wiremock_1  | -----------------------------------------------------------------------------------------------------------------------
wiremock_1  | | Closest stub                                             | Request                                                  |
wiremock_1  | -----------------------------------------------------------------------------------------------------------------------
wiremock_1  |                                                            |
wiremock_1  | GET                                                        | POST                                                <<<<< HTTP method does not match
wiremock_1  | /api/assisted-install/v1/clusters/11111111-1111-1111-1111  | /api/assisted-install/v1/clusters/11111111-1111-1111-1111
wiremock_1  | -111111111111/hosts/00000000-0000-0000-0000-000000000009/  | -111111111111/hosts/00000000-0000-0000-0000-000000000009/
wiremock_1  | instructions                                               | instructions
wiremock_1  |                                                            |
wiremock_1  |                                                            |
wiremock_1  | -----------------------------------------------------------------------------------------------------------------------
wiremock_1  |
wiremock_1  | 2021-03-01 11:37:10.019
wiremock_1  |                                                Request was not matched
wiremock_1  |                                                =======================
wiremock_1  |
wiremock_1  | -----------------------------------------------------------------------------------------------------------------------
wiremock_1  | | Closest stub                                             | Request                                                  |
wiremock_1  | -----------------------------------------------------------------------------------------------------------------------
wiremock_1  |                                                            |
wiremock_1  | GET                                                        | POST                                                <<<<< HTTP method does not match
wiremock_1  | /api/assisted-install/v1/clusters/11111111-1111-1111-1111  | /api/assisted-install/v1/clusters/11111111-1111-1111-1111
wiremock_1  | -111111111111/hosts/00000000-0000-0000-0000-000000000009/  | -111111111111/hosts/00000000-0000-0000-0000-000000000009/
wiremock_1  | instructions                                               | instructions
wiremock_1  |                                                            |
wiremock_1  |                                                            |
wiremock_1  | -----------------------------------------------------------------------------------------------------------------------
wiremock_1  |
wiremock_1  | 2021-03-01 11:37:19.666 No response could be served as there are no stub mappings in this WireMock instance.
wiremock_1  | 2021-03-01 11:37:49.245 No response could be served as there are no stub mappings in this WireMock instance.
wiremock_1  | 2021-03-01 11:38:01.511 No response could be served as there are no stub mappings in this WireMock instance.
wiremock_1  | 2021-03-01 11:38:12.971 No response could be served as there are no stub mappings in this WireMock instance.
wiremock_1  | 2021-03-01 11:38:55.344 No response could be served as there are no stub mappings in this WireMock instance.
wiremock_1  | 2021-03-01 11:39:29.054
wiremock_1  |                                                Request was not matched
wiremock_1  |                                                =======================
wiremock_1  |
wiremock_1  | -----------------------------------------------------------------------------------------------------------------------
wiremock_1  | | Closest stub                                             | Request                                                  |
wiremock_1  | -----------------------------------------------------------------------------------------------------------------------
wiremock_1  |                                                            |
wiremock_1  | GET                                                        | POST                                                <<<<< HTTP method does not match
wiremock_1  | /api/assisted-install/v1/clusters/11111111-1111-1111-1111  | /api/assisted-install/v1/clusters/11111111-1111-1111-1111<<<<< URL does not match
wiremock_1  | -111111111111/hosts/00000000-0000-0000-0000-000000000015/  | -111111111111/hosts
wiremock_1  | instructions                                               |
wiremock_1  |                                                            |
wiremock_1  |                                                            |
wiremock_1  | -----------------------------------------------------------------------------------------------------------------------
wiremock_1  |
wiremock_1  | 2021-03-01 11:39:34.061
wiremock_1  |                                                Request was not matched
wiremock_1  |                                                =======================
wiremock_1  |
wiremock_1  | ------------------------------------------------------------------------------------------------- [...]

2021-03-01 12:03 UTC, YuviGold approved these changes

2021-03-01 12:04 UTC, nmagnezi commented
/unhold

2021-03-01 12:06 UTC, osherdp requested changes

2021-03-01 12:06 UTC, osherdp commented on Makefile
> +	-$(MAKE) _test TEST_SCENARIO=subsystem TEST="./subsystem/..." SKIP="system-test"
what's the minus sign does?

2021-03-01 12:06 UTC, osherdp commented on Makefile
> +	$(DOCKER_COMPOSE) logs dhcpd > dhcpd.log &
why we need the ampersand?
maybe we can limit the log lines instead

2021-03-01 12:22 UTC, nmagnezi commented on Makefile
> +	-$(MAKE) _test TEST_SCENARIO=subsystem TEST="./subsystem/..." SKIP="system-test"
stated in commit msg and in the PR main comment: https://github.com/openshift/assisted-installer-agent/pull/167#issue-571952816

2021-03-01 12:22 UTC, nmagnezi commented on Makefile
> +	$(DOCKER_COMPOSE) logs dhcpd > dhcpd.log &
@YuviGold what do you think?

2021-03-01 12:50 UTC, YuviGold commented on Makefile
> +	$(DOCKER_COMPOSE) logs dhcpd > dhcpd.log &
I think we would want to be blocked until all the logs have been streamed to the file, so we will be able to look at all the logs and not part of it.
So I agree with @osherdp that it can be removed.

2021-03-01 12:51 UTC, nmagnezi commented on Makefile
> +	$(DOCKER_COMPOSE) logs dhcpd > dhcpd.log &
Done

2021-03-01 13:03 UTC, osherdp commented
/lgtm

2021-03-01 14:04 UTC, merged