NO-ISSUE Allow @pkliczewski's team to lgtm PRs
openshift/assisted-installer-agent pull request #189
Opened 2021-04-07 15:47 UTC by ronniel1

2021-04-07 15:51 UTC, osherdp requested changes

2021-04-07 15:51 UTC, osherdp commented on OWNERS
> +      - reviewers-only
bad naming
I think we should do ``code-approvers`` and ``code-reviewers`` and put ``code-approvers`` under ``approvers`` and under ``reviewers``

2021-04-07 17:44 UTC, YuviGold commented on OWNERS
> +      - reviewers-only
Or maybe separate into actual teams like `core` and `edge`, etc

2021-06-24 12:57 UTC, jordigilh commented
@pkliczewski can you rebase?

2021-06-24 12:59 UTC, jordigilh commented on OWNERS
> +      - reviewers-only
`reviewers` sounds good to me, unless you expect more teams to join and be granted different roles. By the way, are we following a naming convention based on function or team's name? I think function makes more sense in the long run, but just my $0.02 :smile:

2021-06-24 13:54 UTC, closed without merging

2021-06-24 13:56 UTC, jordigilh commented
> @jordigilh have a look at #212, let me know what you think

looks good to me. Thanks for taking care of it so swiftly :smile:

2021-06-24 13:58 UTC, osherdp commented
don't worry about it :)