MGMT-6498 Capture routing information in inventory
openshift/assisted-installer-agent pull request #199
Opened 2021-05-18 20:29 UTC by jordigilh

* Populates the routing information into the `inventory` structure for both IPv4 and IPv6. 
* The code is a copy & paste from the [source code](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/net/interface.go) of Kubernetes for both the business logic and the test scenarios, but adapted for the agent's use case.
* The PR depends on this [PR](https://github.com/openshift/assisted-service/pull/1752) that adds the Routing fields in the swagger schema.

2021-05-19 08:37 UTC, avishayt requested changes
Need to add routes to "inventory" in swagger

2021-05-26 14:54 UTC, ori-amizur commented on src/inventory/routes.go
> +	routes, err := v4File.extract()
Is there a reason why not to use existing library such as netlink ?
https://pkg.go.dev/github.com/vishvananda/netlink#RouteList

2021-05-26 15:58 UTC, jordigilh commented
> Need to add routes to "inventory" in swagger

It's already covered in this other PR:

https://github.com/openshift/assisted-service/pull/1752

2021-05-26 16:05 UTC, jordigilh commented on src/inventory/routes.go
> +	routes, err := v4File.extract()
None, I was simply not aware of this library. I'll refactor the code and tests accordingly.

2021-06-03 13:13 UTC, jordigilh commented on src/inventory/routes.go
> +func getIPv6DefaultRoutes(h handler) ([]*models.Route, error) {
It would require an if/else to handle the specific use case of Ipv6 where it validates that the GW equals to IPv6zero (for the loopback device):
https://github.com/openshift/assisted-installer-agent/blob/e7883cf8a0d3399742fbeb690f149d14dd74e30f/src/inventory/routes.go#L91-L93
versus IPv4
https://github.com/openshift/assisted-installer-agent/blob/e7883cf8a0d3399742fbeb690f149d14dd74e30f/src/inventory/routes.go#L65-L67
I think it could cause more confusion to merge both functions because of this particular scenario.

2021-06-03 13:17 UTC, jordigilh commented on src/inventory/routes.go
> +func getIPv6DefaultRoutes(h handler) ([]*models.Route, error) {
I'll update the code with the `IsUnspecified()` method. Looks much better :smile:

2021-06-03 13:23 UTC, jordigilh commented on src/inventory/routes.go
> +func getIPv6DefaultRoutes(h handler) ([]*models.Route, error) {
I take it back: yes, we can merge both methods into one. Turns out that the GW for both IPv4 and IPv6 are zero, so we're good :smile:

2021-06-09 12:34 UTC, ori-amizur commented on src/inventory/routes.go
> +		logrus.Errorf("Unable to retrieve the IPv6 routes: %s", err)
Please fix the error message

2021-06-09 12:48 UTC, jordigilh commented on src/inventory/routes.go
> +		logrus.Errorf("Unable to retrieve the IPv6 routes: %s", err)
done

2021-06-09 13:07 UTC, ori-amizur commented
/lgtm

2021-06-09 13:14 UTC, closed without merging