MGMT-9344: Return non-zero exit when subsystem test fails
openshift/assisted-installer-agent pull request #297
Opened 2022-03-01 14:02 UTC by adriengentil

As part of moving the subsystem test to prow, we need to know when the
step that runs the test fails.

2022-03-01 14:03 UTC, adriengentil commented
/cc @osherdp

2022-03-01 14:07 UTC, omertuc commented on Makefile
> +_pre_subsystem:
target should be PHONY

2022-03-01 14:07 UTC, omertuc commented on Makefile
> +_post_subsystem:
same here

2022-03-01 14:08 UTC, osherdp requested changes

2022-03-01 14:08 UTC, osherdp commented on Makefile
> +	$(MAKE) _test TEST_SCENARIO=subsystem TIMEOUT=30m TEST="$(or $(TEST),./subsystem/...)" || ($(MAKE) _post_subsystem && /bin/false)
it means we only cleanup on success?

2022-03-01 14:08 UTC, osherdp commented on Makefile
> +subsystem: build-image
in your release PR this will allow you to use "public" makefile targets (and not ones like ``_<name>``)?

2022-03-01 14:08 UTC, osherdp commented on Makefile
> +	$(MAKE) _test TEST_SCENARIO=subsystem TIMEOUT=30m TEST="$(or $(TEST),./subsystem/...)" || ($(MAKE) _post_subsystem && /bin/false)
not only cleanup, but also gathering

2022-03-01 14:08 UTC, omertuc commented on Makefile
> +	$(MAKE) _pre_subsystem
```suggestion
subsystem: build-image _pre_subsystem
```

2022-03-01 14:10 UTC, omertuc commented
How is splitting up this target into pre, do, post achieving the goal of the PR?

2022-03-01 14:18 UTC, osherdp commented
> How is splitting up this target into pre, do, post achieving the goal of the PR?

I think because it used to be:
```
-$(MAKE) _test TEST_SCENARIO=subsystem TIMEOUT=30m TEST="$(or $(TEST),./subsystem/...)"
```

so the minus sign at start of the line made it to ignore return code

2022-03-01 14:18 UTC, adriengentil commented on Makefile
> +	$(MAKE) _test TEST_SCENARIO=subsystem TIMEOUT=30m TEST="$(or $(TEST),./subsystem/...)" || ($(MAKE) _post_subsystem && /bin/false)
the trick is in the `|| ($(MAKE) _post_subsystem && /bin/false)`.
If `_test` target fails, the command after the `||` will be executed and since it return a non-zero (`/bin/false`), make will stop the process.

We use the same logic to run the unit tests: https://github.com/openshift/assisted-installer-agent/blob/master/Makefile#L44

@omertuc I think it answers your question

2022-03-01 14:21 UTC, osherdp commented on Makefile
> +	$(MAKE) _test TEST_SCENARIO=subsystem TIMEOUT=30m TEST="$(or $(TEST),./subsystem/...)" || ($(MAKE) _post_subsystem && /bin/false)
sorry, I meant "we only cleanup on failure"
not sure it's that critical though, just an observation

2022-03-01 14:22 UTC, adriengentil commented on Makefile
> +subsystem: build-image
I'm not sure to understand your question, but I don't change the interface so will we still launch the subsystem tests using `make subsystem`

2022-03-01 14:22 UTC, osherdp commented on Makefile
> +	$(MAKE) _test TEST_SCENARIO=subsystem TIMEOUT=30m TEST="$(or $(TEST),./subsystem/...)" || ($(MAKE) _post_subsystem && /bin/false)
ah no, all good
please ignore

2022-03-01 14:24 UTC, omertuc commented on Makefile
> +	$(MAKE) _test TEST_SCENARIO=subsystem TIMEOUT=30m TEST="$(or $(TEST),./subsystem/...)" || ($(MAKE) _post_subsystem && /bin/false)
I get what you're doing but I feel it's a bit hard to follow. rather than short-circuiting / `/bin/false` tricks, maybe we can do something like this pseudocode:

```
// Run the tests, record the result
result = run_tests()

// Cleanup, ignore cleanup failures
cleanup || true

// Return the test result
exit $result
```

2022-03-01 15:39 UTC, adriengentil commented on Makefile
> +	$(MAKE) _test TEST_SCENARIO=subsystem TIMEOUT=30m TEST="$(or $(TEST),./subsystem/...)" || ($(MAKE) _post_subsystem && /bin/false)
Each statement in a makefile is executed in a sub shell which makes things a bit awkward, but I just discovered `.ONESHELL` which could makes things simpler.

https://www.gnu.org/software/make/manual/html_node/One-Shell.html

2022-03-01 16:02 UTC, osherdp commented on Makefile
> +	$(MAKE) _test TEST_SCENARIO=subsystem TIMEOUT=30m TEST="$(or $(TEST),./subsystem/...)" || ($(MAKE) _post_subsystem && /bin/false)
make sure to add a comment when using ``.ONESHELL``, because I think it's not a known feature

2022-03-02 10:38 UTC, adriengentil commented
@omertuc @osherdp I updated my PR, all the statements are now executed in the same shell (thanks to the backslashes) in the `subsystem` target. I think it's cleaner than before, what do you think?

(I mentioned to use `.ONESCRIPT` in a post above, but it applies to the whole makefile, and as @osherdp pointed out, it can be confusing because it's not a well known feature, so I think it's a good idea to use it)

2022-03-02 10:57 UTC, omertuc commented
/lgtm
/approve

2022-03-02 11:53 UTC, osherdp approved these changes
yes, it's cleaner

2022-03-02 12:44 UTC, merged

2022-03-02 16:03 UTC, adriengentil commented
/cherry-pick release-ocm-2.4