AGENT-204: Multi-arch support for OCP build
openshift/assisted-installer-agent pull request #356
Opened 2022-05-19 00:45 UTC by pawanpinjarkar

Ref: https://issues.redhat.com/browse/AGENT-204

2022-05-19 01:04 UTC, pawanpinjarkar commented
Local testing result
![Screenshot from 2022-05-18 21 03 31](https://user-images.githubusercontent.com/25144485/169180344-fcf6ffd8-69be-4186-bb1c-ee934bedb205.jpeg)

2022-05-19 07:13 UTC, osherdp requested changes

2022-05-19 07:13 UTC, osherdp commented on Dockerfile.ocp
> +RUN if [[ "$(arch)" == "x86_64" ]]; then INSTALL_PKGS="biosdevname dhclient dmidecode file findutils fio ipmitool iputils nmap openssh-clients podman chrony smartmontools" && dnf install -y $INSTALL_
just to make it easier on the eye:
```suggestion
RUN if [[ "$(arch)" == "x86_64" ]]; then \
    INSTALL_PKGS="dhclient dmidecode file findutils fio ipmitool iputils nmap openssh-clients podman chrony smartmontools biosdevname"; else \
    INSTALL_PKGS="dhclient dmidecode file findutils fio ipmitool iputils nmap openssh-clients podman chrony smartmontools"; fi \
    && dnf install -y $INSTALL_PKGS && dnf clean all
```

2022-05-19 08:48 UTC, tsorya commented on Dockerfile.ocp
> +RUN if [[ "$(arch)" == "x86_64" ]]; then INSTALL_PKGS="biosdevname dhclient dmidecode file findutils fio ipmitool iputils nmap openssh-clients podman chrony smartmontools" && dnf install -y $INSTALL_
not nicer just to install install all packages that are the same in one line and special x86 one in another one?

2022-05-19 08:53 UTC, osherdp commented on Dockerfile.ocp
> +RUN if [[ "$(arch)" == "x86_64" ]]; then INSTALL_PKGS="biosdevname dhclient dmidecode file findutils fio ipmitool iputils nmap openssh-clients podman chrony smartmontools" && dnf install -y $INSTALL_
Also an option, while not supporting providing two non-inclusive lists
Anything that is not just one long line of code

2022-05-19 11:08 UTC, empovit commented
/uncc empovit

2022-05-19 19:35 UTC, pawanpinjarkar commented on Dockerfile.ocp
> +RUN if [[ "$(arch)" == "x86_64" ]]; then INSTALL_PKGS="biosdevname dhclient dmidecode file findutils fio ipmitool iputils nmap openssh-clients podman chrony smartmontools" && dnf install -y $INSTALL_
Done

2022-05-19 19:39 UTC, osherdp requested changes

2022-05-19 19:39 UTC, osherdp commented on Dockerfile.ocp
> +RUN dnf clean all
nit: ``INSTALL_PKGS`` in current implementation is redundant
instead:
```suggestion
RUN if [[ "$(arch)" == "x86_64" ]]; then dnf install -y biosdevname && dnf clean all; fi
RUN dnf install -y dhclient dmidecode file findutils fio ipmitool iputils nmap openssh-clients podman chrony smartmontools" && dnf clean all
```

2022-05-19 21:47 UTC, celebdor commented
I agree that the variable is not useful in the way it is done. It doesn't hurt either...
/lgtm

2022-05-19 22:06 UTC, lranjbar commented
I agree with the nit. I think this is alright for now since we have a larger problem it seems in assisted-service.

/approve

2022-05-24 19:08 UTC, osherdp commented
/hold
```
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
```

2022-05-25 14:15 UTC, osherdp approved these changes

2022-05-25 14:32 UTC, pawanpinjarkar commented
/hold cancel

2022-05-25 16:14 UTC, lranjbar commented
/remove-downstream-change-needed

2022-05-25 16:26 UTC, merged