NO_ISSUE: fix mock generation.
openshift/assisted-installer-agent pull request #380
Opened 2022-06-16 21:01 UTC by michaellevy101

go generate command failed when the package uses the generated code
The make generate target deletes the old mocks before regenerating them
mocks.go file used util.MockInterface type so after the deletion the compilation failed which fails the mock generation for this package
Using mock.Mock embedded object instead

2022-06-18 19:44 UTC, michaellevy101 commented
@omertuc

2022-06-19 05:29 UTC, osherdp requested changes

2022-06-19 05:29 UTC, osherdp commented on src/inventory/interfaces_test.go
> +func newInterface(mtu int, name string, macAddr string, flags net.Flags, addrs []string, speedMbps int64, interfaceType string) *util.MockInterface {
``newInterface`` seems like the real deal, maybe:
```suggestion
func newMockInterface(mtu int, name string, macAddr string, flags net.Flags, addrs []string, speedMbps int64, interfaceType string) *util.MockInterface {
```

2022-06-19 05:29 UTC, osherdp commented on src/util/test_utils.go
> +		return &net.IPNet{}
seems weird to return an empty value when tester entered malformed values
it's harder to debug those cases

2022-06-19 05:29 UTC, osherdp commented on src/util/test_utils.go
> +func str2Addr(addrStr string) net.Addr {
```suggestion
func parseAddress(addrStr string) net.Addr {
```

2022-06-19 05:29 UTC, osherdp commented on src/util/test_utils.go
> +func toAddresses(addrs []string) []net.Addr {
```suggestion
func parseAddresses(addrs []string) []net.Addr {
```

2022-06-19 05:29 UTC, osherdp commented on src/inventory/interfaces_test.go
> +			newInterface(1400, "bond0", "f8:75:a4:a4:00:fd", net.FlagBroadcast|net.FlagUp, []string{"10.0.0.21/24", "192.168.6.10/20", "fe80::d832:8def:dd51:3529/125", "de90::d832:8def:dd51:3529/125"}, -1, "b
seems like the intention was to have it as a bond address (with the ``isBonding=true`` parameter), same goes with the physical address 
it's worth returning those parameters so that we'll have the same "coverage" as before

2022-06-19 05:29 UTC, osherdp commented on src/util/mocks.go
> +}
can you add a blank line at the end?

2022-06-19 05:29 UTC, osherdp commented on src/scanners/machine_uuid_scanner_test.go
> +	interfaceMock := agentutils.MockInterface{}
Is it possible to have one ``newInterface`` implementation? (in ``test_utils.go`` probably)

2022-06-19 05:31 UTC, osherdp commented
Seems like we have 2 other problems with code generation in this repo:
1. we're replacing code in ``vendor`` dir as well
2. we have no CI job to validate code generation

but those can be handled regardless of this PR

2022-06-19 07:34 UTC, michaellevy101 commented on src/util/test_utils.go
> +		return &net.IPNet{}
It was copied from another file. Not sure if I understand the logic correctly.
It is only a technical PR to prevent the mock generation from failing

2022-06-19 07:34 UTC, michaellevy101 commented on src/util/test_utils.go
> +func str2Addr(addrStr string) net.Addr {
Please read my previous comment

2022-06-19 07:38 UTC, michaellevy101 commented on src/util/test_utils.go
> +func str2Addr(addrStr string) net.Addr {
please read my previous comment. I will change the function name

2022-06-19 07:42 UTC, michaellevy101 commented on src/inventory/interfaces_test.go
> +			newInterface(1400, "bond0", "f8:75:a4:a4:00:fd", net.FlagBroadcast|net.FlagUp, []string{"10.0.0.21/24", "192.168.6.10/20", "fe80::d832:8def:dd51:3529/125", "de90::d832:8def:dd51:3529/125"}, -1, "b
The purpose of this PR is not logic, but to fix the mock generation.
Anyhow, if I understand correctly, we replace the flags with a string value for interfaceType.

2022-06-19 07:44 UTC, michaellevy101 commented on src/scanners/machine_uuid_scanner_test.go
> +	interfaceMock := agentutils.MockInterface{}
unfortunately i don't know. you can't import a test file from another....

2022-06-19 07:46 UTC, michaellevy101 commented on src/scanners/machine_uuid_scanner_test.go
> +	interfaceMock := agentutils.MockInterface{}
maybe adding a separated test package but it isn't so clear

2022-06-19 07:58 UTC, osherdp requested changes

2022-06-19 07:58 UTC, osherdp commented on src/scanners/machine_uuid_scanner_test.go
> +	interfaceMock := agentutils.MockInterface{}
wait, not sure I understand
you import ``FillInterfaceMock`` from ``test_utils.go``. why not import ``newMockInterface`` from the same ``test_utils.go``?

2022-06-19 07:58 UTC, osherdp commented on src/inventory/interfaces_test.go
> +			newInterface(1400, "bond0", "f8:75:a4:a4:00:fd", net.FlagBroadcast|net.FlagUp, []string{"10.0.0.21/24", "192.168.6.10/20", "fe80::d832:8def:dd51:3529/125", "de90::d832:8def:dd51:3529/125"}, -1, "b
I was referring to the missing ``isVlan`` usage, which should be considered as logic-change (that we don't want to have in this PR)
But now I'm seeing it was unused even before, so it should probably be okay to remove

2022-06-19 08:19 UTC, michaellevy101 commented
https://github.com/openshift/assisted-installer-agent/pull/380#discussion_r901064264
@osherdp During regenerating, we delete all generated resources, so any files using a generated type will not compile.
A compilation error prevents the mockery tool from generating the resources. 
Specifically. The mocks.go file uses MockInterface, so mockery is unable to regenerate it because mocks.go has a compilation problem after deleting MockInterface

2022-06-19 08:28 UTC, osherdp commented
> [#380 (comment)](https://github.com/openshift/assisted-installer-agent/pull/380#discussion_r901064264) @osherdp During regenerating, we delete all generated resources, so any files using a generated type will not compile. A compilation error prevents the mockery tool from generating the resources. Specifically. The mocks.go file uses MockInterface, so mockery is unable to regenerate it because mocks.go has a compilation problem after deleting MockInterface This problem can be solved by using MockInterface type by the test and having mocks.go deal with the mock.Mock objet that is embedded inside the generate type. "go build" command ignores test files

ack, it's now more clear
thanks!

2022-06-19 08:40 UTC, osherdp approved these changes

2022-06-19 10:14 UTC, michaellevy101 commented
/retest

2022-06-19 10:56 UTC, merged