MGMT-10936: Cleanup agent code for commands that are not run as with podman run anymore
openshift/assisted-installer-agent pull request #386
Opened 2022-06-26 10:52 UTC by tsorya

MGMT-10936: Cleanup agent code for commands that are not run as with podman run anymore

2022-06-26 11:03 UTC, osherdp requested changes

2022-06-26 11:03 UTC, osherdp commented on Dockerfile.ocp
> -COPY --from=builder /go/src/github.com/openshift/assisted-installer-agent/build/connectivity_check /usr/bin/connectivity_check
if it hasn't been done already, it's worth to do those changes in D/S Dockerfiles prior to merging this PR

2022-06-26 11:03 UTC, osherdp commented on test.py
> +#!/usr/bin/env python
what's this?
same question for the ``sys`` file

2022-06-26 11:08 UTC, tsorya commented on test.py
> +#!/usr/bin/env python
oops

2022-06-26 11:10 UTC, tsorya commented on Dockerfile.ocp
> -COPY --from=builder /go/src/github.com/openshift/assisted-installer-agent/build/connectivity_check /usr/bin/connectivity_check
not sure regarding prior to merging. They actually independent and we can merge this and then downstream. In any case first we should be sure we want to it and that everything works

2022-06-27 06:51 UTC, osherdp approved these changes

2022-06-27 09:24 UTC, tsorya commented
/hold

2022-06-28 17:48 UTC, gamli75 commented
the DS changes were merged https://code.engineering.redhat.com/gerrit/c/assisted-installer-projects/+/417254

2022-06-28 17:49 UTC, gamli75 commented
/remove downstream-change-needed

2022-06-28 17:51 UTC, gamli75 commented
/remove-label downstream-change-needed

2022-08-30 16:11 UTC, tsorya commented
/unhold

2022-09-07 15:08 UTC, osherdp approved these changes

2022-09-07 15:11 UTC, osherdp commented
/lgtm
/refresh

2022-09-07 20:45 UTC, merged