MGMT-13111: Stop agent on `404 Not Found`
openshift/assisted-installer-agent pull request #478
Opened 2023-01-06 19:34 UTC by jhernand

Currently when the user deletes a host the next step runner receives a `404 Not Found` response code from the service, logs it and tries again with exponential backoff. After approximately 15 minutes it stops retrying and exits, and then the main process of the agent will register the host again. The net result is that the host is automatically re-added after those 15 minutes, and we don't want that. To avoid that this patch changes the next step runner so that it stops the agent using the equivalent of `systemctl stop agent.service`. To register the host again the user will have to start the agent or else reboot the host.

Related: https://issues.redhat.com/browse/MGMT-13111

2023-01-18 15:11 UTC, filanov commented
/assign @ori-amizur 
/assign @carbonin

2023-01-18 16:45 UTC, carbonin requested changes
Doesn't this effectively revert the decisions made in https://issues.redhat.com/browse/MGMT-11551?

In that case it was a 404 that caused the agent to sleep forever and we decided that _wasn't_ the behavior we wanted.

Maybe we should at least hit the timeout before stopping the agent rather than doing the stop on the first 404 we get?

2023-01-18 16:45 UTC, carbonin commented on src/service/stop.go
> +const systemdUnitName = "agent.service"
Nit, but can you define this before the function? It just seems strange to me to put it here.

2023-01-22 12:32 UTC, avishayt commented
Why does it exit after 15 minutes?

2023-01-23 09:03 UTC, jhernand commented
@carbonin yes, it partially reverts those decisions, in particular for 404.

@avishayt it exists after 15 minutes because that is the maximum total retry time.

If we don't want to stop the agent in this case we can change that maximum time to infinite.

2023-01-23 13:28 UTC, carbonin commented on src/commands/step_processor.go
> +			err = service.Stop()
This looks like the agent service is being stopped as soon as we get a 404 from the service. Where is the 15 minutes logic?

2023-05-30 12:51 UTC, jhernand commented on src/service/stop.go
> +const systemdUnitName = "agent.service"
Done.

2023-05-30 15:21 UTC, carbonin commented
I still think we should keep the 15 minutes retry around, but stop the whole agent process after that time rather than the previous behavior which would lead to it restarting.

Or am I misunderstanding something?

2023-05-31 06:22 UTC, avishayt commented
The issue of backup/DR has come up recently.  In that case, it makes sense that the agent would receive 404 errors, and then the service would recover.  I suggest we keep the behavior of retrying forever for 404.

2023-05-31 06:35 UTC, jhernand commented
> The issue of backup/DR has come up recently. In that case, it makes sense that the agent would receive 404 errors, and then the service would recover. I suggest we keep the behavior of retrying forever for 404.

Then this change doesn't make sense, I am closing it.

2023-05-31 06:35 UTC, closed without merging