AGENT-502: Add agent based installer agent-tui
openshift/assisted-installer-agent pull request #482
Opened 2023-01-13 00:11 UTC by celebdor

agent-tui is a utility that allows for terminal user interface based reconfiguration of networking/registry.

This first commit contains the current proof of concept level of the code. It currently compiles it dynamically due to centos stream 8 and stream9 missing the nmstate-static package. This means that if one wants to extract the binary, the libnmstate.so should also be copied (or be already present) in the target system.

Signed-off-by: Antoni Segura Puimedon <antoni@redhat.com>

2023-01-13 08:55 UTC, andfasano commented
/retest-required

2023-01-13 09:16 UTC, romfreiman commented
What's the size of the binary?

2023-01-13 09:41 UTC, omertuc commented
>What's the size of the binary?

For the record, it's only included in the ART image of the agent, not the one used by Assisted in SaaS/ACM

2023-01-13 10:50 UTC, omertuc requested changes
Initial review

2023-01-13 10:50 UTC, omertuc commented on src/agent-tui/forms/regnode.go
> +					fmt.Fprintf(statusView, "[red::b]Failed to connect to %s[black]\n%s", addr, tview.Escape(string(output)))
Could also be nice to show the error (if there was some issue running the executable itself)

```suggestion
					fmt.Fprintf(statusView, "[red::b]Failed to connect to %s (%s)[black]\n%s", addr, err, tview.Escape(string(output)))
```

2023-01-13 10:50 UTC, omertuc commented on src/agent-tui/main/main.go
> +package main
Can you create `src/agent-tui/README.md` that explains the general purpose of this utility, most notably the fact that it only applies to BILLI, and maybe some details of how / when users are supposed to reach out for it

2023-01-13 10:50 UTC, omertuc commented on src/agent-tui/main/main.go
> +			//netStatePage, err := modalNetStateJSONPage(&netState, pages)
```suggestion
```

2023-01-13 10:50 UTC, omertuc commented on src/agent-tui/forms/regnode.go
> +		SetLabelColor(tcell.ColorBlack)
Not sure why but in 2 different terminals it's barely legible yellow:

![image](https://user-images.githubusercontent.com/10882062/212300607-f0f3d0a0-db70-43f7-ac86-7b61ccd61f26.png)

2023-01-13 10:51 UTC, omertuc commented
Not sure why the name of one of the interfaces has a different color than the rest

![image](https://user-images.githubusercontent.com/10882062/212302895-9b37769e-519d-41af-b6b1-2031aae8c9de.png)

2023-01-13 10:53 UTC, omertuc commented on src/agent-tui/forms/regnode.go
> +	//height := 40
```suggestion
	width := 80
```

2023-01-13 10:59 UTC, omertuc commented on src/agent-tui/main/main.go
> +func doneView(app *tview.Application, pages *tview.Pages) func(int, string) {
Unused function?

2023-01-13 11:00 UTC, omertuc commented on src/agent-tui/forms/regnode.go
> +				app.Stop()
What happens after this stage? Do we simply expect the networking configuration performed by the user to automatically be applied on the node post-reboot via the coreos-installer's `--copy-network` installation flag?

2023-01-16 14:23 UTC, celebdor commented on src/agent-tui/net/net.go
> +				panic(fmt.Errorf("Multiple default routes. Need to code this"))
Done

2023-01-16 14:23 UTC, celebdor commented on src/agent-tui/main/main.go
> +		SetText("Do you wish for this node to be the one that runs the installation service (Only one node may perform this function)?").
Done

2023-01-16 14:37 UTC, celebdor commented on src/agent-tui/forms/regnode.go
> +					fmt.Fprintf(statusView, "[red::b]Failed to connect to %s[black]\n%s", addr, tview.Escape(string(output)))
Agreed

2023-01-16 14:50 UTC, celebdor commented on src/agent-tui/main/main.go
> +package main
Done. Thanks for the suggestion

2023-01-16 14:52 UTC, celebdor commented on src/agent-tui/main/main.go
> +			//netStatePage, err := modalNetStateJSONPage(&netState, pages)
Done

2023-01-16 15:10 UTC, celebdor commented on src/agent-tui/forms/regnode.go
> +		SetLabelColor(tcell.ColorBlack)
Fixed. Adding the InputField to the Form was making the Form re-style the label of the InputField

2023-01-16 15:12 UTC, celebdor commented
> Not sure why the name of one of the interfaces has a different color than the rest
> 
> ![image](https://user-images.githubusercontent.com/10882062/212302895-9b37769e-519d-41af-b6b1-2031aae8c9de.png)

To indicate it is the default gw interface

2023-01-16 15:14 UTC, celebdor commented on src/agent-tui/forms/regnode.go
> +	//height := 40
Done

2023-01-16 15:17 UTC, celebdor commented on src/agent-tui/forms/regnode.go
> +				app.Stop()
Not tested yet. The idea is indeed that --copy-network will handle it.

2023-01-18 13:41 UTC, andfasano commented on src/agent_tui/net/validations.go
> +	return exec.Command("ping", "-c", "4", address).CombinedOutput()
I guess this could be done directly in go, but that's something we could review later once landed

2023-01-18 13:41 UTC, andfasano commented on src/agent_tui/README.md
> +In the first case, it will perform some checks to determine if the installation can proceed. If it all the checks come
```suggestion
In the first case, it will perform some checks to determine if the installation can proceed. If all the checks come
```

2023-02-16 11:28 UTC, andfasano commented
Requires https://github.com/openshift/release/pull/36356

2023-02-17 08:19 UTC, andfasano commented
/retest-required

2023-02-17 10:55 UTC, omertuc commented
/test edge-unit-test

2023-02-21 09:54 UTC, andfasano commented
/retest

2023-02-21 13:37 UTC, andfasano commented
/retest

2023-02-22 14:07 UTC, andfasano commented
/retest-required

2023-02-23 11:02 UTC, andfasano commented
/lgtm

2023-02-23 13:18 UTC, omertuc commented
/remove-label downstream-change-neede

2023-02-23 13:19 UTC, omertuc commented
> /remove-label downstream-change-needed

2023-02-23 16:22 UTC, merged