MGMT-13420: Adding cleanup of next-step-runner before starting it.
openshift/assisted-installer-agent pull request #484
Opened 2023-01-22 16:16 UTC by tsorya

MGMT-13420: Adding cleanup of next-step-runner before starting it.
In 4.12 for unknown reason podman fails to cleanup next-step-runner on agent restart and --rm doesn't help. To workaround the problem we are adding cleanup before starting it.

2023-01-22 16:22 UTC, osherdp requested changes

2023-01-22 16:22 UTC, osherdp commented on src/commands/actions/next_step_runner.go
> +const containerName = "next-step-runner"
let's reuse this var on line 78, to make sure we don't change it only on one place (and forget the other place)

2023-01-22 16:32 UTC, osherdp approved these changes

2023-01-22 17:56 UTC, omertuc commented
Please check if this also resolves https://issues.redhat.com/browse/MGMT-13183

2023-01-22 18:26 UTC, tsorya commented
@omertuc seems like it should handle it

2023-01-22 19:01 UTC, merged

2023-01-23 07:31 UTC, tsorya commented
/retitle MGMT-13427:Adding cleanup of next-step-runner before starting it

2023-01-23 07:36 UTC, tsorya commented
/cherry-pick release-ocm-2.7