[WIP] MGMT-2380 Update README
openshift/assisted-installer-agent pull request #50
Opened 2020-10-12 11:58 UTC by empovit

2020-10-12 12:00 UTC, empovit commented
/cc @ori-amizur @danielerez

2020-10-12 12:01 UTC, empovit commented
IMO it would be easier just to open the file and read through it, instead of looking at the diff.

2020-10-12 13:20 UTC, empovit commented
/cc @ronniel1

2020-10-12 15:01 UTC, YuviGold requested changes

2020-10-12 15:01 UTC, YuviGold commented on README.md
> +The agent uses the **ghw** library to generate unique uuid identifying the host that the agent is running on.
It has a lot more libraries. What does it matter to specify this certain lib?

2020-10-12 15:07 UTC, empovit commented on README.md
> +the agent shoud run as root. If running in a container, the docker or podman should be invoked with `--net=host` and `--privileged` flags.
Right, will change that.

2020-10-12 15:16 UTC, empovit commented on README.md
> +* Docker
Will add

2020-10-12 15:22 UTC, empovit commented on README.md
> +* *--inventory-image*: The name of the inventory image.  Default is "quay.io/ocpmetal/inventory:latest".
It _is_ inventory, but probably isn't needed. Good catch!

2020-10-12 15:23 UTC, empovit commented on README.md
> +The agent uses the **ghw** library to generate unique uuid identifying the host that the agent is running on.
Looks like it, but I guess the original author had a good reason to do so.

2020-10-12 15:58 UTC, mhrivnak requested changes

2020-10-12 15:58 UTC, mhrivnak commented on README.md
> +The agent uses the **ghw** library to generate unique uuid identifying the host that the agent is running on.
A link would be valuable here.

2020-10-12 15:58 UTC, mhrivnak commented on README.md
> +This projects generates several products, each packaged as a Docker image:
s/Docker image/container image/

2020-10-12 15:58 UTC, mhrivnak commented on README.md
> +the agent shoud run as root. If running in a container, the docker or podman should be invoked with `--net=host` and `--privileged` flags.
s/shoud/should/

2020-10-12 15:58 UTC, mhrivnak commented on README.md
> +* Docker
When run in an RHCOS live ISO, doesn't it use podman?

2020-10-12 16:04 UTC, empovit commented on README.md
> +This projects generates several products, each packaged as a Docker image:
"binary"?

2020-10-12 16:06 UTC, empovit commented on README.md
> +* Docker
Docker is needed for subsystem testing. For now at least.

2020-10-12 16:11 UTC, mhrivnak commented on README.md
> +* Docker
It's probably worth noting then that it is just a testing dependency, and not a runtime dependency.

2020-10-14 08:51 UTC, danielerez commented on README.md
> +This projects contains several executables that are intended to run in tandem with the
hmm, nothing crucial, but just not sure about 'tandem' :)
maybe: 'intended to be invoked by...' or 'intended to run along with...'

2020-10-14 08:51 UTC, danielerez commented on README.md
> +[OpenShift Assisted Installation Service](https://github.com/openshift/assisted-service):
iinm, it's commonly named 'installer service'

2020-10-14 08:51 UTC, danielerez commented on README.md
> +Since the agent is a statically linked go executable, it can be copied and ran outside a container. If running outside a container,
s/ran/run

2020-10-15 17:13 UTC, empovit commented on README.md
> +The agent uses the **ghw** library to generate unique uuid identifying the host that the agent is running on.
Apparently the library plays an important role in inventory collection, I updated this with a link to it repo.

2020-10-15 17:46 UTC, tsorya commented
/lgtm

2020-10-15 17:46 UTC, tsorya commented
/approve

2020-10-19 08:11 UTC, ori-amizur approved these changes
/lgtm

2020-10-19 08:14 UTC, merged