MGMT-15507: Set restricted list of approvers for protected release-ocm-2.9 branch
openshift/assisted-installer-agent pull request #600
Opened 2023-09-11 12:27 UTC by eliorerz

/cc @filanov @gamli75 @romfreiman

2023-09-19 16:58 UTC, osherdp approved these changes

2023-10-02 08:54 UTC, filanov approved these changes

2023-10-02 08:56 UTC, filanov commented
/hold
the target branch is master?

2023-10-02 09:00 UTC, filanov requested changes
please make sure you merge it into release-ocm-2.9

2023-10-10 08:13 UTC, closed without merging