MGMT-17867: fix multipath inventory to include wwn
openshift/assisted-installer-agent pull request #733
Opened 2024-06-27 12:24 UTC by linoyaslan

Currently, if the cluster has multipath configured, the multipath inventory does not include the WWN. This occurs because the `ghw` package returns "unknown" if it fails to detect the WWN, and we then set it to empty. With my changes, if `ghw` returns "unknown," the code retrieves the WWN differently and returns it instead of an empty string.

2024-06-27 12:25 UTC, linoyaslan commented
/cc @avishayt @eliorerz

2024-06-27 12:33 UTC, avishayt requested changes

2024-06-27 12:33 UTC, avishayt commented on src/inventory/disks.go
> +		}
This logic doesn't really belong in "unknownToEmpty"

2024-06-27 12:33 UTC, avishayt commented on src/inventory/disks.go
> +func unknownToEmpty(value string, defaultVal string) string {
It's no longer changing to "Empty"

2024-06-27 12:33 UTC, avishayt commented on src/inventory/disks.go
> +		return diskPath, wwn
I think it would be cleaner to leave this, and add a method to remove "/dev/disk/by-id" and "wwn-"

2024-06-27 12:34 UTC, linoyaslan commented
/cc @danmanor

2024-06-27 14:13 UTC, danmanor commented on src/inventory/disks.go
> +func getPureWWN(wwn string, byId string) string {
Why is this parameter called `byId` ?

2024-06-27 14:21 UTC, avishayt commented
Please use consts and add a unit test

2024-06-27 14:26 UTC, linoyaslan commented on src/inventory/disks.go
> +func getPureWWN(wwn string, byId string) string {
@danmanor Because the argument being sent is the by-id param of the disk
```
ByID:                    diskPath2diskWWN[path],
Wwn:                     getPureWWN(disk.WWN, diskPath2diskWWN[path]),
```

2024-06-30 05:54 UTC, linoyaslan commented
/retest

2024-06-30 09:26 UTC, avishayt approved these changes

2024-06-30 09:26 UTC, avishayt commented
/lgtm

2024-06-30 10:39 UTC, linoyaslan commented
/retest

2024-06-30 12:43 UTC, merged

2026-04-01 03:30 UTC, zaneb reviewed
I believe this code is effectively dead since #936 updated to a version of ghw that supports returning the WWN for multipath disks. We should probably consider reverting to reduce confusion in future.

2026-04-01 03:30 UTC, zaneb commented on src/inventory/disks.go
> +		withoutPrefix := strings.TrimPrefix(byId, prefix)
This will return a wrong value if the disk does not start with `wwn-` (`nvme-eui` is also a valid possibility from line 55).