NO-ISSUE-fix-broken-build: Fix broken build due to base image change.
openshift/assisted-installer-agent pull request #761
Opened 2024-07-31 06:02 UTC by paul-maidment

The image registry.access.redhat.com/ubi9/go-toolset:1.20 does not default to the root user as registry.ci.openshift.org/openshift/release:golang-1.20 used to This results in a permissions issue when attempting to run `go mod download`

By setting the user directive prior to this operation, this PR resolves that issue

2024-07-31 07:40 UTC, danmanor commented
/lgtm

2024-07-31 07:40 UTC, danmanor commented
/approve

2024-07-31 08:36 UTC, rccrdpccl commented
/hold

where is this failing?

2024-07-31 11:42 UTC, rccrdpccl commented
For the records we discuss this and it happens also outside skipper, due to misalignment of permissions.

2024-07-31 11:42 UTC, rccrdpccl commented
/lgtm
/approve

2024-07-31 11:42 UTC, rccrdpccl commented
/unhold

2024-07-31 12:00 UTC, danmanor commented
why not just use `root` in the base image as done initially ?

2024-08-01 07:30 UTC, eifrach requested changes

2024-08-01 07:30 UTC, eifrach commented on Dockerfile.assisted_installer_agent
> +COPY --chown=1001 go.mod .
let's keep it simple and same as other builds
just set the user for the build stage 

same as the controller
https://github.com/openshift/assisted-installer/blob/master/Dockerfile.assisted-installer#L7

2024-08-01 12:21 UTC, rccrdpccl commented
> why not just use root in the base image as done initially ? @rccrdpccl @paul-maidment
The base image is meant to be used differently, using the home folder instead of pre-go mod style of folder for the module being compiled.
I think it would be easier to understand to use it that way and there is no real need to use root user.

That said, in this specific case it's not a real disadvantage using root.

2024-08-01 12:22 UTC, rccrdpccl commented on Dockerfile.assisted_installer_agent
> +COPY --chown=1001 go.mod .
I understand the root user approach is used everywhere else, but as [stated in the comments](https://github.com/openshift/assisted-installer/blob/master/Dockerfile.assisted-installer#L6) it's a workaround, while this would be the expected way of building golang projects with this base image.

2024-08-01 12:23 UTC, rccrdpccl commented
/retest

2024-08-01 15:22 UTC, rccrdpccl commented
/hold
Let's make sure we agree on the solution before unholding
I'm ok with both but I think the current one (using the home directory) is better.

/retest

flake

2024-08-01 16:21 UTC, rccrdpccl commented
/retest

2024-09-05 07:57 UTC, rccrdpccl commented
/lgtm

2024-09-05 08:13 UTC, paul-maidment commented
/unhold

2024-09-05 08:17 UTC, merged