ACM-15078: Fixing agents reuse problem in z/VM after reclaim
openshift/assisted-installer-agent pull request #817
Opened 2024-10-28 04:25 UTC by veera-damisetti

- Updated bootLoaderConfigTemplateS390x to add ai.ip_cfg_override to take care of IP and nameserver parameters , which is a mandatory parameter in z/VM as mac address is not persistent. 
- Updated paramaters which are being passed to zipl , to include parameters from /proc/cmdline which will help in reusing the agents after reclaim.

2024-10-28 15:35 UTC, CrystalChun approved these changes
/lgtm

2024-10-28 15:35 UTC, CrystalChun commented
Would be great to see how and why these additional parameters are needed specifically for Z in order for the hosts to be reusable! Maybe a doc or blog post would be the route to show everyone?

2024-10-28 15:55 UTC, veera-damisetti commented
Sure @CrystalChun 
In order to reuse the hosts, hosts should be booted with proper/desired network and storage configurations.

In case of Z ( z/VM) , 
- IP and nameserver should be added to cmdline parameters , as using NMState is not possible, because mac address is not persistent in z/VM. 
- Network configurations should be included in cmdline parameters, using rd.znet and ip . which through we can give desired network cards for connectivity.
- Similarly, we should give storage configuraions also with rd.zfcp,rd.dasd and zfcp.allow_lun_scan, depends on the type of the disk which we want to configure for z/VM.

HCP IBMZ doc for z/VM for cmdline parameter reference: https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.11/html/clusters/cluster_mce_overview#hosted-bare-metal-adding-agents-ibmz-zvm-lpar

RH doc for explaining more details about each param: https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/7/html/installation_guide/chap-installer-booting-ipl-s390#chap-installer-booting-ipl-s390

2024-10-28 16:09 UTC, veera-damisetti commented
/assign @eifrach

2024-10-29 09:21 UTC, eifrach commented on src/commands/actions/reboot_for_reclaim.go
> +			return stdout, stderr, exitCode
the rest of the code is depending on this.
we should add a stop here

2024-10-29 09:22 UTC, eifrach commented on src/commands/actions/reboot_for_reclaim.go
> +			return stdout, stderr, exitCode
same here, if failed no point of continuing

2024-10-29 09:24 UTC, eifrach commented on src/commands/actions/reboot_for_reclaim.go
> +		}
I think we should create a function for this and a unit test.

once we start to use regex it can break in future changes  + make this function more readable

2024-10-29 09:26 UTC, eifrach commented on src/commands/actions/reboot_for_reclaim.go
> +			match := regex.FindStringSubmatch(stdout)
what happens if we don't have a match ?

2024-10-29 09:31 UTC, eifrach requested changes
how is the unit-test passed without a change?
we are missing here a lot for testing to this logic

2024-10-29 09:43 UTC, veera-damisetti commented on src/commands/actions/reboot_for_reclaim.go
> +			match := regex.FindStringSubmatch(stdout)
If there’s no match for a parameter in stdout, the current code skips over assigning it, so cmdline_params[param] remains unset.
and this should be the expected behaviour, if paramsToExtract  are not present in /proc/cmdline

2024-10-29 12:10 UTC, veera-damisetti commented on src/commands/actions/reboot_for_reclaim.go
> +		}
Sure @eifrach 
Do you want me to write entire s390x logic in a seperate function and unit test ?  or just this fetching parameters using regexp as a seperate function ?

2024-10-31 00:27 UTC, veera-damisetti commented
/test edge-e2e-metal-assisted

2024-10-31 00:31 UTC, veera-damisetti commented
/test edge-subsystem-test

2024-10-31 03:14 UTC, veera-damisetti commented
@eifrach , thanks for the review. 

I did changes to have a separate function for the logic and added unit tests for the same, and 
Please have a look.

2024-10-31 12:39 UTC, eifrach commented on src/commands/actions/reboot_for_reclaim.go
> +		}
yes just the regex / paramter fatching. cause we do want make sure that changes wont break it later on

2024-10-31 12:42 UTC, eifrach commented
/lgtm

2024-10-31 12:46 UTC, eifrach commented
/approve

2024-10-31 12:48 UTC, veera-damisetti commented on src/commands/actions/reboot_for_reclaim.go
> +		}
Sure

2024-10-31 12:53 UTC, merged

2024-10-31 12:59 UTC, veera-damisetti commented
Thanks @CrystalChun @eifrach , for the quick reviews.

2025-02-06 15:20 UTC, carbonin commented
/cherry-pick release-ocm-2.12

2025-02-06 15:22 UTC, carbonin commented
/cherry-pick release-ocm-2.11