MGMT-18464: MGMT-18452: Add validations to make iSCSI disk eligible
openshift/assisted-installer-agent pull request #819
Opened 2024-11-08 17:01 UTC by adriengentil

This PR adds 2 checks before making iSSI disks be be eligible as
installation disk.

MGMT-18464: Check the state of the disk, we need to ensure that it is
"running" otherwise the installtion of RHCOS will fail on the disk.

MGMT-18464: Check if the discovery as been booted using iBFT, this check
ensure that the iSCSI disk is actually a disk on which we will be able
to boot from.

2024-11-08 17:04 UTC, adriengentil commented
/cc @AlonaKaplan @eifrach @rccrdpccl

2024-11-08 17:30 UTC, adriengentil commented
/hold
Might had some more tests

2024-11-08 17:31 UTC, adriengentil commented on src/inventory/disks.go
> +			logrus.WithError(err).Errorf("Failed to read iSCSI target name in iBFT")
```suggestion
			logrus.WithError(err).Errorf("Failed to read iSCSI target name in iBFT")
			continue
```

2024-11-10 06:53 UTC, eifrach commented on src/inventory/disks.go
> +	iSCSIHost, err := d.getISCSIHost(diskName)
maybe we should check this before entering this function.

2024-11-10 06:56 UTC, eifrach commented on src/inventory/disks.go
> +	const ibftBasePath = "/sys/firmware/ibft"
this should move to top of the file with the other const

2024-11-10 07:05 UTC, eifrach commented on src/inventory/disks.go
> +
if those function retruns a string value - should we continue?

2024-11-10 07:11 UTC, eifrach commented on src/inventory/disks.go
> +	if !isISCSIDisk(disk) {
second time we check this - we can check before those two functions once - if it false we can skip both functions

2024-11-10 07:16 UTC, eifrach requested changes
We should think about moving most of the logic to the service and use the agent to collect the information.

In some cases, that might not be a great option. but, by leaving the logic in the service, this will make the agent simpler and allow us to patch the service without needing to redeploy a new agent.

2024-11-12 09:16 UTC, adriengentil commented
>We should think about moving most of the logic to the service and use the agent to collect the information.

in this case the service won't make use of this information, except for validations, that's why I put them here. I don't expect this code to change often, so I think it's ok for the moment to have them here, I will think about moving them in the service if we need further updates and if we need more flexibility.

2024-11-12 09:16 UTC, adriengentil commented on src/inventory/disks.go
> +	if !isISCSIDisk(disk) {
I wanted them to be seft-contained, but ok, that works too.

2024-11-12 09:18 UTC, adriengentil commented on src/inventory/disks.go
> +
this function gathers **all** the possible reasons for a disk to not be eligible for installation, so we need to continue.

2024-11-12 16:16 UTC, adriengentil commented on src/inventory/disks.go
> +	iSCSIHost, err := d.getISCSIHost(diskName)
done

2024-11-12 16:19 UTC, adriengentil commented on src/inventory/disks.go
> +	if !isISCSIDisk(disk) {
done, moved the check out

2024-11-13 08:40 UTC, eifrach commented
/lgtm

2024-11-13 08:44 UTC, adriengentil commented
/unhold

2024-11-13 08:49 UTC, merged