MGMT-2322 Add ntp_synchronizer executable
openshift/assisted-installer-agent pull request #83
Opened 2020-11-09 12:54 UTC by YuviGold

/cc @ori-amizur @ronniel1

2020-11-09 13:17 UTC, ori-amizur commented on subsystem/ntp_test.go
> +		fmt.Println(*source)
Remove Println

2020-11-09 13:17 UTC, ori-amizur commented on subsystem/ntp_test.go
> +		if source.SourceState == models.SourceStateSynced {
The veirifier should just identify the reply.  It should not check states

2020-11-09 13:17 UTC, ori-amizur commented on src/ntp_synchronizer/ntp_synchronizer.go
> +type INTPDependencies interface {
The name is a bit strange - maybe more meaningful ?

2020-11-09 13:17 UTC, ori-amizur commented on src/ntp_synchronizer/ntp_synchronizer.go
> +	stdout, stderr, exitCode := e.Execute("timeout", strconv.FormatInt(ChronyTimeoutSeconds, 10), "chronyc", "-c", "sources")
Why this command with timeout and the previous not? Is the timeout needed?

2020-11-09 13:17 UTC, ori-amizur commented on src/ntp_synchronizer/ntp_synchronizer.go
> +func NtpSync(ntpSyncRequestStr string, executer INTPDependencies, log logrus.FieldLogger) (stdout string, stderr string, exitCode int) {
Maybe create a struct with functions that the executer is a member?

2020-11-09 13:17 UTC, ori-amizur commented on src/ntp_synchronizer/ntp_synchronizer.go
> +	for _, line := range strings.Split(stdout, "\n") {
It makes more sense to first handle the exitCode and if it is OK format the sources.  The formatting can be in its own function

2020-11-09 13:23 UTC, YuviGold commented on src/ntp_synchronizer/ntp_synchronizer.go
> +type INTPDependencies interface {
I was inspired by `Dependencies` from `dhcp_lease_allocator`.

2020-11-09 13:24 UTC, YuviGold commented on src/ntp_synchronizer/ntp_synchronizer.go
> +	stdout, stderr, exitCode := e.Execute("timeout", strconv.FormatInt(ChronyTimeoutSeconds, 10), "chronyc", "-c", "sources")
Not really. I just think it is safer to add a timeout. WDYT?

2020-11-09 13:25 UTC, ori-amizur commented on src/ntp_synchronizer/ntp_synchronizer.go
> +type INTPDependencies interface {
INTPDependecies is a bit strange (I think)

2020-11-09 13:39 UTC, YuviGold commented on src/ntp_synchronizer/ntp_synchronizer.go
> +type INTPDependencies interface {
Ok changing to `NtpSynchronizerDependencies`

2020-11-09 13:40 UTC, YuviGold commented on src/ntp_synchronizer/ntp_synchronizer.go
> +func NtpSync(ntpSyncRequestStr string, executer INTPDependencies, log logrus.FieldLogger) (stdout string, stderr string, exitCode int) {
What for? I can just replace the executer, I don't have any other functions

2020-11-15 17:53 UTC, YuviGold commented
@gamli75 Where do I update the downstream image?

2020-11-15 20:15 UTC, YuviGold commented
/cc @ronniel1 @carbonin

2020-11-17 10:04 UTC, osherdp requested changes

2020-11-17 10:04 UTC, osherdp commented on subsystem/ntp_test.go
> +		numberOfSources int
why should it be global for the whole describe scope, and not used in this scope?
can be local variable in each ``It``

2020-11-17 10:04 UTC, osherdp commented on subsystem/ntp_test.go
> +		Expect(len(ntpResponse.NtpSources)).Should(BeNumerically(">", numberOfSources))
Cannot be asserted against a concrete value?

2020-11-17 10:32 UTC, empovit commented on src/ntp_synchronizer/main/main.go
> +		os.Exit(-1)
Why not use log.Fatalf() whose purpose seems exactly "cannot continue, print error and exit"? https://github.com/sirupsen/logrus/blob/d131c24e23baaa812461202af6d7cfa388e2d292/logger.go#L186

2020-11-17 10:33 UTC, YuviGold commented on src/ntp_synchronizer/ntp_synchronizer.go
> +func formatChronySourcesOutput(output string) *[]*models.NtpSource {
In order to return `nil` and being able to validate it.
In this situation where I'm also retrieving an error (for `GetNTPSources`) maybe it isn't necessary.

2020-11-17 10:34 UTC, empovit commented on src/ntp_synchronizer/main/main.go
> +		os.Exit(-1)
It could also help to tell what the program expects, "exactly single argument" is too general (I know we do it in other commands, too).

2020-11-17 10:35 UTC, YuviGold commented on subsystem/ntp_test.go
> +		numberOfSources = len(ntpResponse.NtpSources)
Because the NTP executable on subsystem runs with `--net=host` I'm unable to know the amount of expected NTP sources (it is dependent on the running machine. It might be zero).
So I just wanted to make sure I can get a response, and in the next test I'm verifying that when adding a new server - the amount of NTP sources is increased.

2020-11-17 10:36 UTC, YuviGold commented on subsystem/ntp_test.go
> +		numberOfSources int
Explained in the previous comment.

2020-11-17 10:37 UTC, YuviGold commented on subsystem/ntp_test.go
> +		Expect(len(ntpResponse.NtpSources)).Should(BeNumerically(">", numberOfSources))
Explained in the previous comment.

2020-11-17 10:40 UTC, YuviGold commented on src/ntp_synchronizer/main/main.go
> +		os.Exit(-1)
As you said, I was just copying other commands' behavior. But your suggestion seems cleaner :) 
@ori-amizur Do we care if the exit error would be `-1` as we currently do or `1` as returned by `log.Fatalf()`?

2020-11-17 10:55 UTC, osherdp commented on subsystem/ntp_test.go
> +		numberOfSources = len(ntpResponse.NtpSources)
then use _ so it will be clear

2020-11-17 10:56 UTC, osherdp commented on subsystem/ntp_test.go
> +		numberOfSources = len(ntpResponse.NtpSources)
So there is dependencies between the tests?
I don't think it's good...

2020-11-17 11:03 UTC, empovit commented on subsystem/ntp_test.go
> +		numberOfSources = len(ntpResponse.NtpSources)
I agree with @osherdp

2020-11-17 11:08 UTC, YuviGold commented on subsystem/ntp_test.go
> +		numberOfSources = len(ntpResponse.NtpSources)
Alright

2020-11-17 11:12 UTC, osherdp requested changes

2020-11-17 11:12 UTC, osherdp commented on subsystem/ntp_test.go
> +func (i *NTPSynchronizerVerifier) verify(actualReply *models.StepReply) bool {
We need in other issue to replace those verifiers with ones that return errors
It's bad that we separate between validation failure and it's reason (logs are not displayed as the bottom line)

2020-11-17 14:47 UTC, ori-amizur commented on subsystem/ntp_test.go
> +func (i *NTPSynchronizerVerifier) verify(actualReply *models.StepReply) bool {
Don't agree.  Verifiers are just for indication if a message is from a particular type.  error is not relevant here

2020-11-17 14:50 UTC, ori-amizur commented on src/ntp_synchronizer/main/main.go
> +		os.Exit(-1)
We need to output to stderr in this case.  This way, it will be logged and transferred to assisted-service.

2020-11-17 14:52 UTC, ori-amizur commented on src/ntp_synchronizer/ntp_synchronizer.go
> +	stdout, stderr, exitCode := e.Execute("timeout", strconv.FormatInt(ChronyTimeoutSeconds, 10), "chronyc", "-c", "sources")
Do you want to fail it on timeout?

2020-11-17 14:56 UTC, osherdp commented on subsystem/ntp_test.go
> +func (i *NTPSynchronizerVerifier) verify(actualReply *models.StepReply) bool {
We're writing logs and returning a general boolean indication that something bad happened. The first thing being shown if the test fails is that generic message, and the real root cause needs to be then tracked
Why not just error or alternatively use the same assertion-like mechanism of ginkgo?

2020-11-17 14:57 UTC, ori-amizur commented on src/ntp_synchronizer/main/main.go
> +		os.Exit(-1)
@YuviGold Fatalf is OK.  Just make sure to output the error to stderr.

2020-11-17 15:03 UTC, YuviGold commented on src/dhcp_lease_allocate/lease.go
> +	case util.TimeoutExitCode:
Previously we resolved the hostnames, now it's only IPs.
Anyway, I think it is better to wrap a timeout scenario just in case.

2020-11-17 15:25 UTC, YuviGold commented on subsystem/ntp_test.go
> +func (i *NTPSynchronizerVerifier) verify(actualReply *models.StepReply) bool {
I agree with @osherdp to propagate the error instead of boolean. But it would require to change all of the interface implementations so that's for another PR. :)

2020-11-17 16:20 UTC, carbonin commented on src/ntp_synchronizer/ntp_synchronizer.go
> +type NtpSynchronizerDependencies interface {
An interface should be named after what it does. So in this case I would suggest `Executor`.

Also all of this seems like it shouldn't be the ntp-specific package's problem, I think the `util` package should provide this interface.

2020-11-17 16:20 UTC, carbonin commented on src/ntp_synchronizer/ntp_synchronizer.go
> +func GetNTPSources(e NtpSynchronizerDependencies) ([]*models.NtpSource, error) {
Why is this exported?

2020-11-17 16:20 UTC, carbonin commented on src/ntp_synchronizer/ntp_synchronizer.go
> +	var ntpSyncRequest models.NtpSynchronizationRequest
These variable names could be simplified. We're in a function called `NtpSync` I don't think all the variables should be prefixed with `ntpSync`.

`requestStr` and `request` would be better.
Also `s/executer/executor/`

2020-11-17 16:20 UTC, carbonin commented on src/ntp_synchronizer/ntp_synchronizer.go
> +		log.WithError(err).Errorf("NTPSync: json.Unmarshal")
Can these be more like sentences? Maybe something like:

```suggestion
		log.WithError(err).Errorf("Failed to unmarshal ntp request string %s", ntpSyncRequestStr)
```

Same goes for pretty much every error message in this function

2020-11-17 16:20 UTC, carbonin commented on src/ntp_synchronizer/ntp_synchronizer.go
> +func NtpSync(ntpSyncRequestStr string, executer NtpSynchronizerDependencies, log logrus.FieldLogger) (stdout string, stderr string, exitCode int) {
We only ever return `0` or `-1` for `exitCode`, can we remove it and decide what code to use in the caller?

2020-11-17 16:20 UTC, carbonin commented on src/ntp_synchronizer/ntp_synchronizer.go
> +func NtpSync(ntpSyncRequestStr string, executer NtpSynchronizerDependencies, log logrus.FieldLogger) (stdout string, stderr string, exitCode int) {
I think a more standard go return value would be `(string, error)`.
Then in the caller we would print the error text to stderr (if we got an error) and the string to stdout.

2020-11-18 08:04 UTC, YuviGold commented on src/ntp_synchronizer/ntp_synchronizer.go
> +	stdout, stderr, exitCode := e.Execute("timeout", strconv.FormatInt(ChronyTimeoutSeconds, 10), "chronyc", "-c", "sources")
Yes

2020-11-18 08:38 UTC, YuviGold commented on Makefile
> +GOTEST_FLAGS = --format=standard-verbose $(GOTEST_PUBLISH_FLAGS) -- -count=1 -cover -coverprofile=$(REPORTS)/$(TEST_SCENARIO)_coverage.out
Its output is more verbose.

2020-11-18 08:52 UTC, YuviGold commented on src/ntp_synchronizer/ntp_synchronizer.go
> +func GetNTPSources(e NtpSynchronizerDependencies) ([]*models.NtpSource, error) {
No certain reason. Just thought it might be useable in the future as a utility.
But I guess it would never be used, so I changed it back to be private.

2020-11-18 08:56 UTC, YuviGold commented on src/ntp_synchronizer/ntp_synchronizer.go
> +type NtpSynchronizerDependencies interface {
This is how we create the dependencies mostly to be generated for mocks in the UT.

2020-11-18 09:07 UTC, YuviGold commented on src/ntp_synchronizer/ntp_synchronizer.go
> +func NtpSync(ntpSyncRequestStr string, executer NtpSynchronizerDependencies, log logrus.FieldLogger) (stdout string, stderr string, exitCode int) {
Just copied the skeleton from another utility. :) I agree with you. I'll make these changes on a different PR.

2020-11-18 09:12 UTC, YuviGold commented on src/ntp_synchronizer/main/main.go
> +	if flag.NArg() != 1 {
I created a JIRA ticket [MGMT-2961](https://issues.redhat.com/browse/MGMT-2961) with utility enhancements.

2020-11-18 09:27 UTC, osherdp commented
/lgtm

2020-11-19 09:22 UTC, YuviGold commented
/remove-label downstream-change-needed

2020-11-19 09:23 UTC, osherdp commented
/lgtm

2020-11-19 09:24 UTC, merged