OCPBUGS_45910: Fix cpu clockspeed for s390x
openshift/assisted-installer-agent pull request #857
Opened 2024-12-16 13:23 UTC by apodvrat

For s390x architectures lscpu does not return the clock speed by "CPU MHz" or "CPU max MHz" field but have two fields (CPU static MHz and CPU dynamic MHz). 
"CPU static MHz" is the field representing the designed clock speed whereas the "CPU dynamic MHz" is representing the current CPU speed (throttled or energy saving).
New test case for s390x architecture was added. 

The fix was tested using unit tests:

JUnit path was configured: ./junit_unit_test.xml

JUnit report was created: /root/code/Assisted_Installer/latest/assisted-installer-agent/src/inventory/junit_unit_test.xml

Ran 121 of 121 Specs in 0.268 seconds
SUCCESS! -- 121 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestInventory (0.30s)

2024-12-17 08:18 UTC, AmadeusPodvratnik commented
/retest

2024-12-17 11:58 UTC, AmadeusPodvratnik commented
/retest

2024-12-17 13:52 UTC, apodvrat commented
/retest

2024-12-17 15:00 UTC, paul-maidment commented on src/inventory/cpu.go
> +		case "Model name", "Machine type":
Might be worth a mention in the commit message that "Machine Type" is used in place of "Model name" in S390x `lscpu` responses.

2024-12-17 16:11 UTC, apodvrat commented on src/inventory/cpu.go
> +		case "Model name", "Machine type":
Thank you for the comment. Done.

2024-12-18 07:44 UTC, apodvrat commented
/retest

2024-12-18 09:41 UTC, AmadeusPodvratnik commented
/retest

2024-12-18 15:52 UTC, paul-maidment requested changes

2024-12-18 15:52 UTC, paul-maidment commented on src/inventory/cpu_test.go
> +			Flags: []string{"esan3", "zarch", "stfle" "msa", "ldisp", "eimm", "dfp", "edat", "etf3eh", "highgprs", "te", "vx",
I missed this on first glance but the reason your tests are failing is that you are missing a comma between "stfle" and "msa"

2024-12-19 08:55 UTC, apodvrat commented on src/inventory/cpu_test.go
> +			Flags: []string{"esan3", "zarch", "stfle" "msa", "ldisp", "eimm", "dfp", "edat", "etf3eh", "highgprs", "te", "vx",
:-) Thank you ... I saw this bug but I'm dealing with two different development system because of my two different git account (IBM and RH) and fixed it only on one ... but it should work now ...

2024-12-20 18:44 UTC, apodvrat commented
/retest

2025-01-07 10:27 UTC, apodvrat commented
/retest

2025-01-07 12:28 UTC, paul-maidment commented
/override ci/prow/edge-e2e-oci-assisted-4-18

2025-01-07 12:28 UTC, paul-maidment commented
/override ci/prow/okd-scos-e2e-aws-ovn

2025-01-07 12:29 UTC, paul-maidment commented
/lgtm

2025-01-07 12:32 UTC, paul-maidment commented
/jira refresh

2025-01-07 12:43 UTC, apodvrat commented
/jira refresh

2025-01-07 12:46 UTC, apodvrat commented
/jira refresh

2025-01-07 12:49 UTC, apodvrat commented
/jira refresh

2025-01-08 11:07 UTC, AmadeusPodvratnik commented
/retest

2025-01-08 11:37 UTC, AmadeusPodvratnik commented
/retest

2025-01-08 15:14 UTC, paul-maidment commented
/lgtm

2025-01-08 16:29 UTC, apodvrat commented
/retest

2025-01-08 16:58 UTC, merged

2025-01-08 17:16 UTC, apodvrat commented
/cherry-pick release-4.18