OCPBUGS-43352: calculate outgoing interface for arping
openshift/assisted-installer-agent pull request #877
Opened 2024-12-22 15:27 UTC by eifrach

2024-12-24 13:15 UTC, eifrach commented
/test ?

2024-12-24 13:16 UTC, eifrach commented
/test e2e-agent-compact-ipv4
/test edge-subsystem-test

2024-12-24 15:18 UTC, paul-maidment commented on src/connectivity_check/ipv4_arping_checker.go
> +			// Ignore exit code of 1; only 2 or -1 are actual errors
The `w` parameter is a timeout parameter and provided that this is higher than `c` then arping will await all responses, if it receives all responses, a zero exit code will be retuned.

At the very least I think we should mention the reason for receiving a non zero exit code.

```
paulmaidment@fedora ~ $ arping -c 6 -w 6 -I wlp0s20f3 192.168.20.1
ARPING 192.168.20.1 from 192.168.20.76 wlp0s20f3
Unicast reply from 192.168.20.1 [74:44:01:47:AA:34]  1.534ms
Unicast reply from 192.168.20.1 [74:44:01:47:AA:34]  1.489ms
Unicast reply from 192.168.20.1 [74:44:01:47:AA:34]  2.832ms
Unicast reply from 192.168.20.1 [74:44:01:47:AA:34]  4.550ms
Unicast reply from 192.168.20.1 [74:44:01:47:AA:34]  2.089ms
Unicast reply from 192.168.20.1 [74:44:01:47:AA:34]  2.830ms
Sent 6 probes (1 broadcast(s))
Received 6 response(s)
paulmaidment@fedora ~ $ echo $?
0
```

2024-12-25 13:51 UTC, eifrach commented
/test e2e-agent-compact-ipv4
/test edge-subsystem-test
/test images
/test edge-lint
/test edge-unit-test

2024-12-25 13:53 UTC, eifrach commented
/test e2e-agent-compact-ipv4
/test edge-subsystem-test
/test images
/test edge-lint
/test edge-unit-test

2024-12-25 14:25 UTC, eifrach commented on src/connectivity_check/ipv4_arping_checker.go
> +			// Ignore exit code of 1; only 2 or -1 are actual errors
I agree  but, I wonder where the information about the status code came from. ( on [commit](https://github.com/openshift/assisted-installer-agent/commit/d9b910b53544808ea726d8239d4b3cf3b31bc320) )

@zaneb  can you share where did you get the status codes? and/or what arpping version is it based on ?

2024-12-26 09:53 UTC, linoyaslan commented on src/connectivity_check/ipv4_arping_checker_test.go
> +			OutgoingNIC:        OutgoingNic{Name: outgoingNIC, HasIpv4Addresses: true, Addresses: getAddr(outgoingIPAddress, 24)},
How about adding a new test where the remote address is not in the same network as the local IP? bc currently, all the scenarios only include cases where both the local and remote IPs are in the same network.

2024-12-26 15:48 UTC, eifrach commented
/test e2e-agent-compact-ipv4
/test edge-subsystem-test
/test images
/test edge-lint
/test edge-unit-test

2024-12-26 15:49 UTC, eifrach commented on src/connectivity_check/ipv4_arping_checker.go
> +			// Ignore exit code of 1; only 2 or -1 are actual errors
after some checking,  it does fail on error code 1 - when there is no ping to the host. 
I've refactor it a bit and added a wait for ping before checking the arpping which makes it pass every time.

let me know what you think @paul-maidment

2024-12-29 08:13 UTC, eifrach commented
/test e2e-agent-compact-ipv4
/test edge-unit-test

2024-12-29 10:33 UTC, paul-maidment commented on src/connectivity_check/ipv4_arping_checker.go
> +			// Ignore exit code of 1; only 2 or -1 are actual errors
Your changes in this area look good :)

2024-12-30 15:26 UTC, paul-maidment commented
/lgtm

2025-01-05 12:54 UTC, eifrach commented
/test edge-unit-test

2025-01-06 12:30 UTC, eifrach commented on src/connectivity_check/ipv4_arping_checker_test.go
> +			OutgoingNIC:        OutgoingNic{Name: outgoingNIC, HasIpv4Addresses: true, Addresses: getAddr(outgoingIPAddress, 24)},
thanks for the input, Done I've added a test for remote address is not in the same subnet of the outgoing interface

2025-01-06 14:14 UTC, paul-maidment requested changes

2025-01-06 14:14 UTC, paul-maidment commented on src/connectivity_check/ipv4_arping_checker.go
> +				log.Warn("ARPPing exited with error code 1, ignoring")
I still think we should make sure that we got at least one successful ping here. It is actually possible to force a return code of `1` when there is an erorr.

```
paulmaidment@paulmaidment:~$ sudo arping -c 6 -w 6 -I enp0s8 192.168.209.1
ARPING 192.168.209.1
Timeout
Timeout
Timeout
Timeout
Timeout
Timeout

--- 192.168.209.1 statistics ---
6 packets transmitted, 0 packets received, 100% unanswered (0 extra)

paulmaidment@paulmaidment:~$ echo $?
1
```

I think we should at least say 

```
"ARPPing did not receive all ping responses back but received at least one, ignoring.
```

2025-01-06 14:18 UTC, eifrach commented on src/connectivity_check/ipv4_arping_checker.go
> +				log.Warn("ARPPing exited with error code 1, ignoring")
@AlonaKaplan can we get you're input on this?

2025-01-06 14:28 UTC, paul-maidment requested changes

2025-01-06 14:28 UTC, paul-maidment commented on src/connectivity_check/ipv4_arping_checker.go
> +				log.Warn("ARPPing exited with error code 1, ignoring")
Suggest we just add a comment above the log entry

```
// The return code of 1 will be returned when there are some missing replies (possibly all of them)
// as we are looking for "duplicate" replies and are not concerned with missing replies, we may ignore this.
```

2025-01-06 14:31 UTC, eifrach commented on src/connectivity_check/ipv4_arping_checker.go
> +				log.Warn("ARPPing exited with error code 1, ignoring")
thanks for the input

2025-01-06 14:31 UTC, eifrach commented
/override ci/prow/edge-e2e-oci-assisted-4-18

2025-01-06 14:34 UTC, paul-maidment approved these changes
/lgtm

2025-01-06 14:55 UTC, eifrach commented
/override ci/prow/edge-e2e-oci-assisted-4-18

2025-01-07 07:26 UTC, eifrach commented
/override ci/prow/okd-scos-e2e-aws-ovn

2025-01-07 07:46 UTC, eifrach commented
/jira refresh

2025-01-07 07:47 UTC, eifrach commented
/jira refresh

2025-01-07 07:48 UTC, eifrach commented
/jira refresh

2025-01-07 07:48 UTC, eifrach commented
/jira refresh

2025-01-07 07:49 UTC, eifrach commented
/jira refresh

2025-01-07 07:53 UTC, merged

2025-02-03 03:37 UTC, zaneb commented on src/connectivity_check/ipv4_arping_checker.go
> +			// Ignore exit code of 1; only 2 or -1 are actual errors
I believe [this](https://github.com/iputils/iputils/blob/20210202/arping.c) is the version in RHEL 9.
It has been largely rewritten since [the version in RHEL 8](https://github.com/iputils/iputils/blob/s20180629/arping.c), and now things that for decades used to work, don't.
I do not believe a single word the man page has to say about this.

2025-02-03 03:53 UTC, zaneb commented on src/connectivity_check/ipv4_arping_checker.go
> +			// Ignore exit code of 1; only 2 or -1 are actual errors
It looks like that man page quote comes from a [bug fix](https://github.com/iputils/iputils/commit/854873bdd28fcdd9cc3fe0c2d29c083a07d07a86) that is not (yet) present in RHEL9.

2025-08-29 15:07 UTC, andfasano commented
/cherry-pick release-4.18

2025-08-29 15:20 UTC, andfasano commented
retitling the PR to allow the cherry-pick bot works as expected

/retitle OCPBUGS-43352: calculate outgoing interface for arping

2025-08-29 15:21 UTC, andfasano commented
/cherry-pick release-4.18