MGMT-2951 - Will log reasons for why disks were skipped
openshift/assisted-installer-agent pull request #98
Opened 2020-11-24 08:39 UTC by omertuc

We have many reasons to skip disks as installation candidates - we will now log all the reasons why skip a certain disk when we do, to aid in troubleshooting installation problems

2020-11-24 08:58 UTC, osherdp requested changes

2020-11-24 08:58 UTC, osherdp commented on src/inventory/disks.go
> +				"Disk (name %s bus path %s vendor %s model %s) was found to be irrelevant for the following reasons:\n %s",
Maybe you can get along with only ``%s`` the disk model? I remember most of the information is there
But check me, I might be wrong

2020-11-24 08:58 UTC, osherdp commented on src/inventory/disks.go
> +		{func() bool { return disk.IsRemovable }, "Disk is removeable"},
Maybe replace the functions usage with something like
```
if disk.IsRemovable {
    disqualifyingReasons = append(disqualifyingReasons, "Disk is removable")
}
if ...
return disqualifyingReasons
```

2020-11-24 08:58 UTC, osherdp commented on src/inventory/disks.go
> +			logrus.Infof(
replace with debug

2020-11-24 08:58 UTC, osherdp commented on src/inventory/disks.go
> +				disk.Name, disk.BusPath, disk.Vendor, disk.Model, reasonsLines)
Is it possible to squeeze in partitions data as well?

2020-11-24 08:58 UTC, osherdp commented on src/inventory/disks.go
>  	return false
We should consider splitting the conditions of fstype and mountpoint, I'm not happy with what I did :)

2020-11-24 09:06 UTC, osherdp commented
also add some tests

2020-11-24 09:35 UTC, omertuc commented on src/inventory/disks.go
> +			logrus.Infof(
What's the reason? I assumed debug logs are turned off by default. Do we usually have debug logs enabled/stored? This seems important enough to always be available in the logs. It should only happen once anyway so it doesn't really spam.

2020-11-24 09:46 UTC, osherdp commented on src/inventory/disks.go
> +			logrus.Infof(
You're right, it seems like debug is turned off
Nice catch :)

2020-11-24 09:50 UTC, omertuc commented on src/inventory/disks.go
> +				disk.Name, disk.BusPath, disk.Vendor, disk.Model, reasonsLines)
Haven't messed around with the disks in practice, which partition information do you think is interesting to include in this log? For each partition we have the following fields:
```
type Partition struct {
	Disk       *Disk  `json:"-"`
	Name       string `json:"name"`
	Label      string `json:"label"`
	MountPoint string `json:"mount_point"`
	SizeBytes  uint64 `json:"size_bytes"`
	Type       string `json:"type"`
	IsReadOnly bool   `json:"read_only"`
}
```

2020-11-24 10:38 UTC, osherdp commented on src/inventory/disks.go
> +				disk.Name, disk.BusPath, disk.Vendor, disk.Model, reasonsLines)
default format seems fine I think
https://github.com/jaypipes/ghw/blob/master/pkg/block/block.go#L209

Maybe @yevgeny-shnaidman have other ideas

2020-11-24 11:28 UTC, omertuc commented on src/inventory/disks.go
> +				"Disk (name %s bus path %s vendor %s model %s) was found to be irrelevant for the following reasons:\n %s",
Doesn't seem so, here's an example from my laptop:
```
+block storage (5 disks, 713GB physical storage)
Disk &block.Disk{Name:"dm-0", SizeBytes:0x3b37d00000, PhysicalBlockSizeBytes:0x200, DriveType:4, IsRemovable:false, StorageController:0, BusPath:"unknown", NUMANodeID:0, Vendor:"unknown", Model:"unknown", SerialNumber:"unknown", WWN:"unknown", Partitions:[]*block.Partition{}}
Disk &block.Disk{Name:"dm-1", SizeBytes:0x117f400000, PhysicalBlockSizeBytes:0x200, DriveType:4, IsRemovable:false, StorageController:0, BusPath:"unknown", NUMANodeID:0, Vendor:"unknown", Model:"unknown", SerialNumber:"unknown", WWN:"unknown", Partitions:[]*block.Partition{}}
Disk &block.Disk{Name:"dm-2", SizeBytes:0x3e8000000, PhysicalBlockSizeBytes:0x200, DriveType:4, IsRemovable:false, StorageController:0, BusPath:"unknown", NUMANodeID:0, Vendor:"unknown", Model:"unknown", SerialNumber:"unknown", WWN:"unknown", Partitions:[]*block.Partition{}}
Disk &block.Disk{Name:"dm-3", SizeBytes:0x25d0800000, PhysicalBlockSizeBytes:0x200, DriveType:4, IsRemovable:false, StorageController:0, BusPath:"unknown", NUMANodeID:0, Vendor:"unknown", Model:"unknown", SerialNumber:"unknown", WWN:"unknown", Partitions:[]*block.Partition{}}
Disk &block.Disk{Name:"nvme0n1", SizeBytes:0x3b9e656000, PhysicalBlockSizeBytes:0x200, DriveType:4, IsRemovable:false, StorageController:3, BusPath:"pci-0000:2e:00.0-nvme-1", NUMANodeID:0, Vendor:"unknown", Model:"SAMSUNG MZVLB256HBHQ-000L7", SerialNumber:"S4ELNX0N663432", WWN:"eui.0025388601b396fe", Partitions:[]*block.Partition{(*block.Partition)(0xc00015ab60), (*block.Partition)(0xc00015abd0), (*block.Partition)(0xc00015ac40)}}
	Partition  nvme0n1p1 (600MB) [vfat] mounted@/boot/efi
	Partition  nvme0n1p2 (1GB) [ext4] mounted@/boot
	Partition  nvme0n1p3 (237GB) 

```

2020-11-24 11:30 UTC, omertuc commented on src/inventory/disks.go
> +				disk.Name, disk.BusPath, disk.Vendor, disk.Model, reasonsLines)
Will use default format then

2020-11-24 12:41 UTC, osherdp commented on src/inventory/disks.go
> +		{func() bool { return disk.IsRemovable }, "Disk is removeable"},
What your thought of this matter?
The code is currently not readable

2020-11-24 13:36 UTC, omertuc commented on src/inventory/disks.go
> +		{func() bool { return disk.IsRemovable }, "Disk is removeable"},
I've modified the formatting to make this more readable for now. If you still think it's not readable I'll change it to `if`'s

2020-11-24 13:40 UTC, omertuc commented
> also add some tests

I think adding tests to make sure the correct `info` log is being logged is a bit excessive. There are already existing tests to make sure disks are skipped when they need to be skipped, and these tests are passing.

2020-11-24 13:47 UTC, osherdp commented on src/inventory/disks.go
> +		{func() bool { return disk.IsRemovable }, "Disk is removeable"},
I think it's still not readable

2020-11-25 09:46 UTC, osherdp commented
/lgtm

2020-11-25 11:59 UTC, omertuc commented
/assign osherdp

2020-11-25 12:00 UTC, omertuc commented
/assign @osherdp

2020-11-25 12:01 UTC, osherdp commented
/approve

2020-11-25 12:03 UTC, merged